functionframeworks/frameworks.go, functionframeworks/openfunctioncontext.go, go.mod, main.go, testdata/demo/bindings_function.go
Signed-off-by: laminar <fangtian@yunify.com>
=> init functions-framework-go

functionframeworks/openfunctioncontext.go
Signed-off-by: laminar <fangtian@yunify.com>
=> Change io.ReadAll => ioutil.ReadAll

functionframeworks/frameworks.go, functionframeworks/frameworks_test.go, main.go
remove return of http register
Signed-off-by: laminar <fangtian@yunify.com>
=> fix register

examples/dapr-demos/user-functions/bindings_http_with_output.go, examples/dapr-demos/user-functions/bindings_http_without_output.go
Signed-off-by: laminar <fangtian@kubesphere.io>
=> Change library "io" -> "ioutil" in examples

functionframeworks/frameworks.go, openfunction-context/context.go, openfunction-context/types.go
Rename function return struct from `Return` to `RetValue`.
Signed-off-by: laminar <fangtian@kubesphere.io>
=> Rename function return struct name

README.md
Signed-off-by: laminar <fangtian@yunify.com>
=> docs: init the readme

functionframeworks/frameworks.go, openfunction-context/context.go, openfunction-context/types.go
=> fix: change default dapr grpc client port to "50001"

README.md
=> release v0.1.1

framework/framework.go
log plugin information at function start
=> log plugin information

context/types.go
=> add yaml tags for PluginsTracing struct

context/context.go, plugin/skywalking/test/sync-request/docker/Dockerfile.of, plugin/skywalking/test/sync-request/docker/Dockerfile.provider, runtime/knative/knative.go
https://github.com/OpenFunction/functions-framework-go/runs/5139011442?check_suite_focus=true#step:4:31
=> Fix slice bounds out of range

context/context.go, context/context_test.go, context/innerevent.go
=> Fix and optimize the handling logic of Inputs and Outputs

context/context.go, runtime/knative/knative.go
=> remove ctx.DestroyDaprClient() in knative runtime

README.md
=> update readme to v0.2.0

.github/workflows/main.yml, .github/workflows/plugin_test.yaml, README.md
1. Adjust the listening scope of the github ci
2. Update the readme
=> release v0.2.1

context/context.go, context/context_test.go, plugin/skywalking/test/binding-event/manifests/manifests.yaml, plugin/skywalking/test/sync-request/docker-compose.yml, plugin/skywalking/test/topic-event/manifests/manifests.yaml
=> change field "PluginsTracing.Enable" to "PluginsTracing.Enabled"

.github/workflows/main.yml, go.mod, go.sum
=> upgrade dapr to v1.8.1

plugin/skywalking/test/binding-event/e2e.yaml, plugin/skywalking/test/topic-event/e2e.yaml, test/bindings/e2e.yaml, test/pubsub/e2e.yaml
Signed-off-by: Benjamin Huo <benjamin@kubesphere.io>
=> Upgrade dapr to 1.8.3 for e2e

runtime/runtime.go
fix retry logic of async function
=> fix funcout in async

context/context.go, runtime/runtime.go
do not share function context accross request
=> fix context logic
